# 3 instances of postgres, each one with a fix ip address
# 127.0.0.1, 127.0.0.2 and 127.0.0.3 and default port.
# The compose file is the following:

version: '3.8'

services:
    dl1:
        image: postgres:15-alpine
        container_name: dllocal_dl1
        restart: always
        ports:
            - "127.0.0.1:5432:5432"
            - "54321:5432"
        volumes:
            - ./postgres_dl1:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 1qaz3edc5tgb7ujm9ol.
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres

    dl2:
        image: postgres:15-alpine
        container_name: dllocal_dl2
        restart: always
        ports:
            - "127.0.0.2:5432:5432"
            - "54322:5432"
        volumes:
            - ./postgres_dl2:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 1qaz3edc5tgb7ujm9ol.
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
  
    dl3:
        image: postgres:15-alpine
        container_name: dllocal_dl3
        restart: always
        ports:
            - "127.0.0.3:5432:5432"
            - "54323:5432"
        volumes:
            - ./postgres_dl3:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 1qaz3edc5tgb7ujm9ol.
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres

    dw:
        image: postgres:15-alpine
        container_name: dllocal_dw
        restart: always
        ports:
            - "127.0.0.4:5432:5432"
            - "54324:5432"
        volumes:
            - ./postgres_dw:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 1qaz3edc5tgb7ujm9ol.
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres

volumes:
    postgres_dl1:
    postgres_dl2:
    postgres_dl3:
    postgres_dw: 
